---
title: "NCEAS Coding Club"
---

## Motivations

The National Center for Ecological Analysis and Synthesis' (NCEAS) Coding Club is born from a desire to learn and teach peer-to-peer on all things data science and early career. The main motivation is to create spaces within our workplace that are welcoming, empowering and supportive. Where participants can experiment with their new knowledge, present their ideas, ask questions, and learn from each other.



Based on [Openscapes Seaside Chats](https://www.openscapes.org/seaside-chats/) philosophy, a group of us meet weekly on what we call Data Science Chats (DSC). The goal of these meetings is to talk data science. A place where we discuss data challenges and seek, offer and accept guidance from one another. Topics can be best practices or hack-y work-arounds -- the only guiding light is that you describe some data management/analysis task that you've found helpful (or request a talk on something you *would* find useful!).


For now, we are comprised only of NCEAS employees but we may organically grow beyond that scope given time.


## Other Resources

Scripts produced outside of this website can largely be found in the ["data-science-chats_scripts" GitHub repository](https://github.com/nceas-coding-club/data-science-chats_scripts) though because `git` is **not** prerequisite to joining DSC, not all scripts are placed in that repo.
